inherit_from: configs/mono/tum/base_config.yaml
Dataset:
  dataset_path: /hdd/slam/tum_calib/fr3_office
  Calibration:
    fx: 535.4
    fy: 539.2
    cx: 320.1
    cy: 247.6
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    width: 640
    height: 480
    depth_scale: 5000.0
    distorted: false
  SelfCalibration:
    enabled: true
    radial_distortion: 1
    frame_id: 100, 200, 300
    gt_fx: 500, 560, 500
    gt_kappa: 0.0, 0.0, 0.0
    backend_params:
      lr_cnt1: 0.002
      lr_cnt2: 0.0002
